services:
  - type: web
    name: edupredict-server
    env: node
    rootDirectory: .
    buildCommand: |
      npm install
      pip install -r microservice/requirements.txt
    startCommand: node server.js