services:
- type: web
  name: edupredict-backend
  env: node
  buildCommand: |
    npm install
    python -m pip install --upgrade pip
    python -m pip install -r microservice/requirements.txt
  startCommand: npm start
  envVars:
  - key: MONGO_URI
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: NODE_VERSION
    value: 18