services:
  - type: web
    name: edupredict-server
    env: node
    rootDirectory: .
    buildCommand: |
      npm install
      python3 -m pip install --upgrade pip
      python3 -m pip install -r microservice/requirements.txt
    startCommand: node server.js